CREATE TABLE "author" (
      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
      "name" VARCHAR(255) NOT NULL,
      "date_created" DATE NOT NULL,
      PRIMARY KEY("id")
);

CREATE TABLE "genre" (
     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
     "name" VARCHAR(255) NOT NULL,
     "date_created" DATE NOT NULL,
     PRIMARY KEY("id")
);

CREATE TABLE "book" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "title" VARCHAR(255) NOT NULL,
    "author_id" BIGINT,
    "genre_id" BIGINT,
    "date_created" DATE NOT NULL,
    PRIMARY KEY("id"),
    FOREIGN KEY("author_id") REFERENCES "author"("id") ON UPDATE NO ACTION ON DELETE SET NULL,
    FOREIGN KEY("genre_id") REFERENCES "genre"("id") ON UPDATE NO ACTION ON DELETE SET NULL
);

CREATE TABLE "user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "date_created" DATE NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE "book_loan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "book_id" BIGINT NOT NULL,
    "is_returned" BOOLEAN DEFAULT FALSE,
    "date_return" DATE,
    "date_created" DATE NOT NULL,
    PRIMARY KEY("id"),
    FOREIGN KEY("user_id") REFERENCES "user"("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    FOREIGN KEY("book_id") REFERENCES "book"("id") ON UPDATE NO ACTION ON DELETE CASCADE
);