DROP TABLE IF EXISTS loan_fine CASCADE;
DROP TABLE IF EXISTS book_loan CASCADE;
DROP TABLE IF EXISTS book_reservation CASCADE;
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS author CASCADE;

---

-- Criação da tabela 'author' para armazenar informações dos autores.
CREATE TABLE IF NOT EXISTS author
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) UNIQUE NOT NULL,
    date_created DATE DEFAULT CURRENT_DATE NOT NULL
);

-- Criação da tabela 'genre' para armazenar os gêneros dos livros.
CREATE TABLE IF NOT EXISTS genre
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) UNIQUE NOT NULL,
    date_created DATE DEFAULT CURRENT_DATE NOT NULL
);

-- Criação da tabela 'users' para gerenciar os usuários da biblioteca.
CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    date_created  DATE DEFAULT CURRENT_DATE NOT NULL
);

-- Criação da tabela 'book' para os livros disponíveis na biblioteca.
CREATE TABLE IF NOT EXISTS book
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    author_id    BIGINT REFERENCES author (id) ON DELETE SET NULL,
    genre_id     BIGINT REFERENCES genre (id) ON DELETE SET NULL,
    date_created DATE DEFAULT CURRENT_DATE NOT NULL,
    is_available BOOLEAN DEFAULT TRUE
);

-- Criação da tabela 'book_reservation' para registrar as reservas de livros.
CREATE TABLE IF NOT EXISTS book_reservation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id         BIGINT NOT NULL REFERENCES book (id) ON DELETE CASCADE,
    loan_start_date DATE NOT NULL,
    due_date        DATE NOT NULL
);

-- Criação da tabela 'book_loan' para registrar os empréstimos de livros.
CREATE TABLE IF NOT EXISTS book_loan
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id             BIGINT NOT NULL REFERENCES book (id) ON DELETE CASCADE,
    book_reservation_id BIGINT REFERENCES book_reservation (id) ON DELETE SET NULL,
    loan_date           DATE DEFAULT CURRENT_DATE NOT NULL,
    due_date            DATE NOT NULL,
    return_date         DATE,
    is_returned         BOOLEAN DEFAULT FALSE
);

-- Criação da tabela 'loan_fine' para registrar multas por atraso.
CREATE TABLE IF NOT EXISTS loan_fine
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_loan_id BIGINT UNIQUE NOT NULL REFERENCES book_loan (id) ON DELETE CASCADE,
    cost_per_day NUMERIC(10, 2),
    is_payed     BOOLEAN DEFAULT FALSE
);
